### ISSUE TITLE
Colab code not running

### ISSUE THREAD

**Issue by SaiKeshav** [AI4Bharat/IndicXlit#1]
Hi,

Thanks a lot for sharing the great work! The shared [colab link](https://colab.research.google.com/drive/1P78Tbr6zhe-5LeiKk525N3SGPKn2ofGg?usp=sharing) fails in the last cell with the following error:

```
ImportError                               Traceback (most recent call last)
[<ipython-input-4-f601442c8fb6>](https://localhost:8080/#) in <module>()
      1 from datetime import datetime
----> 2 import xlit_translit
      3 
      4 num_suggestions = 10
      5 

1 frames
[/content/IndicXlit/inference/python/custom_interactive.py](https://localhost:8080/#) in <module>()
     21 import torch
     22 
---> 23 from fairseq import checkpoint_utils, distributed_utils, options, tasks, utils
     24 from fairseq.dataclass.configs import FairseqConfig
     25 from fairseq.dataclass.utils import convert_namespace_to_omegaconf

ImportError: cannot import name 'checkpoint_utils' from 'fairseq' (unknown location)

```
This occurs presumable due to a difference in the version of fairseq. The code by default uses the latest fairseq code in Github, which may have changed from the time this was tested at your end. Could you please check this?

Thanks,
Keshav

**Comment by GokulNC** [comment]
Can you try using our latest library:
https://pypi.org/project/ai4bharat-transliteration/1.0.0/

**Comment by GokulNC** [comment]
Please let us know if you are still facing this issue.
Closing it for now. Thanks!
