### ISSUE TITLE
Unable to install Indic Xlit python library

### ISSUE THREAD

**Issue by alans3321** [AI4Bharat/IndicXlit#39]
Hi,

I am facing this issue ( attached as screenshot) while trying to run pip install ai4bharat-transliteration.

![image](https://github.com/user-attachments/assets/ab42f052-4adb-46bb-80cf-78d90d61eeff)

**Comment by HemanthSai7** [comment]
downgrade your python version to python==3.7 or python==3.8 and then try

**Comment by alans3321** [comment]
Thanks was able to complete the installation by downgrading pip to version 2.4.0
