### ISSUE TITLE
Getting an error : BadZipFile: File is not a zip file

### ISSUE THREAD

**Issue by naynikaw** [AI4Bharat/IndicXlit#4]
![image](https://user-images.githubusercontent.com/42168952/177042620-2e946b0b-d737-4a88-83a5-32ba9422c31a.png)

I am trying to initialize the engine, but am immediately getting the above error

**Comment by GokulNC** [comment]
Thanks for reporting. The issue has been fixed in the latest version now.
Can you please try now after running: `pip install ai4bharat-transliteration==1.0.0.2`
