### ISSUE TITLE
Is there a way to detect the language of a transliterated text and it's probability?a

### ISSUE THREAD

**Issue by bnriiitb** [AI4Bharat/IndicXlit#7]
Is there a way to detect the language of a transliterated text and it's probability?a

Example: 
baagunnara is a transliterated Telugu sentence.  So, given this piece of text can we get the likelihood of the languages? in this case it's Telugu.

**Comment by yashmadhani97** [comment]
No IndicXlit doesn't support language identification given the piece of text. Although we are working on it as a part of another project.
