### ISSUE TITLE
Can you provide some documentation on how to predict using the fine tuned model ?

### ISSUE THREAD

**Issue by GautamR-Samagra** [AI4Bharat/IndicXlit#9]

**Comment by yashmadhani97** [comment]
Hi @GautamR-Samagra, You can use the same inference code for fine-tuned model. Refer to this colab notebook. https://colab.research.google.com/drive/1TurBNE0Pq9_hqEOXps0FXfymsdlJotE0?usp=sharing#scrollTo=WR9f4kma3mds

No, right now fairseq doesn't provide any python interface for inference, you have to use fairseq-interactive or fairseq-generate for inference.
